apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-database
  namespace: orchestrator
  labels:
    app: billing-database
spec:
  serviceName: billing-database-service
  replicas: 1
  selector:
    matchLabels:
      app: billing-database
  template:
    metadata:
      labels:
        app: billing-database
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "billing_db"
        - name: POSTGRES_USER
          value: "ndiogou"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: orchestrator-secret
              key: BILLING_DB_PASSWORD
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - ndiogou
            - -d
            - billing_db
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - ndiogou
            - -d
            - billing_db
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-path"  # CORRIGÉ: utilise local-path au lieu de standard
      resources:
        requests:
          storage: 1Gi