apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-app
  namespace: orchestrator
  labels:
    app: billing-app
spec:
  serviceName: billing-service
  replicas: 1
  selector:
    matchLabels:
      app: billing-app
  template:
    metadata:
      labels:
        app: billing-app
    spec:
      containers:
      - name: billing-app
        image: lamoundios7/billing-app:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: orchestrator-configmap
        - secretRef:
            name: orchestrator-secret
        
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: FLASK_ENV
          value: "development"
        
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
            
        # # Health checks plus tolérants
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 60  # Plus de temps pour l'initialisation
        #   periodSeconds: 30        # Moins fréquent
        #   timeoutSeconds: 10       # Plus de temps
        #   failureThreshold: 5      # Plus tolérant
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 15  # Démarrage rapide
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   failureThreshold: 3
        
        # # PLUS DE SCRIPT DE DÉMARRAGE - démarrage direct
        # # L'application gère elle-même les reconnexions RabbitMQ