apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-database
  namespace: orchestrator
spec:
  serviceName: billing-database
  replicas: 1
  selector:
    matchLabels:
      app: billing-database
  template:
    metadata:
      labels:
        app: billing-database
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
      initContainers:
      - name: init-db
        image: alpine:3.21.3
        securityContext:
          runAsUser: 0  # Nécessaire pour chown
        command: 
        - sh
        - -c
        - |
          echo "Initializing data directory permissions..."
          mkdir -p /var/lib/postgresql/data
          chown -R 999:999 /var/lib/postgresql/data
          chmod 700 /var/lib/postgresql/data
          echo "Permissions set successfully"
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      containers:
      - name: postgres
        image: lamoundios7/billing-database:latest
        securityContext:
          runAsUser: 999
          runAsGroup: 999
          allowPrivilegeEscalation: true  # Nécessaire pour les opérations de gestion d'utilisateur
          capabilities:
            add:
            - CHOWN
            - FOWNER
        ports:
        - containerPort: 5432
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data
        envFrom:
        - configMapRef:
            name: orchestrator-configmap
        - secretRef:
            name: orchestrator-secret
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 45
          periodSeconds: 20
          timeoutSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi