apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-database
  namespace: orchestrator
spec:
  serviceName: billing-database
  replicas: 1
  selector:
    matchLabels:
      app: billing-database
  template:
    metadata:
      labels:
        app: billing-database
    spec:
      securityContext:
        fsGroup: 999
      initContainers:
      - name: init-db
        image: lamoundios7/billing-database:latest
        command: ["sh", "-c", "chown -R 999:999 /var/lib/postgresql/data && su-exec postgres initdb -D /var/lib/postgresql/data/pgdata"]
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
      containers:
      - name: postgres
        image: lamoundios7/billing-database:latest
        securityContext:
          runAsUser: 999
          runAsGroup: 999
        ports:
        - containerPort: 5432
        # env:
        # - name: POSTGRES_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: orchestrator-secret
        #       key: POSTGRES_PASSWORD
        # - name: POSTGRES_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: orchestrator-secret
        #       key: POSTGRES_USER
        # - name: POSTGRES_DB
        #   value: orders
        # - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        envFrom:
        - configMapRef:
            name: orchestrator-configmap
        - secretRef:
            name: orchestrator-secret
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 45
          periodSeconds: 20
          timeoutSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi