apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-configmap
  namespace: orchestrator
data:
  # API Gateway
  PORT: "3000"
  INVENTORY_SERVICE_URL: "http://inventory-app:8080"
  
  # Inventory Database
  INVENTORY_DB_HOST: "inventory-database"
  INVENTORY_DB_PORT: "5432"
  INVENTORY_DB_NAME: "movies_db"
  INVENTORY_DB_USER: "admin"
  
  # Billing Database
  BILLING_DB_HOST: "billing-database"
  BILLING_DB_PORT: "5432"
  BILLING_DB_NAME: "billing_db"
  BILLING_DB_USER: "admin"
  
  # RabbitMQ
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"